version: '3'

services:
    nginx:
      build: .
      ports:
        - 80:80
        - 443:443
      volumes:
        - ../../public:/usr/share/nginx/html
        - ./sites-enabled:/etc/nginx/sites-enabled
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ../mastodon/public/system:/var/www
        - ../wordpress/public:/var/www/html
      environment:
        TZ: Asia/Tokyo
      restart: unless-stopped
      networks:
        - external_network

networks:
    external_network:
      external: true