version: '3'

services:
  app:
    container_name: shadowban-alerts
    image: ghcr.io/iamtakagi/shadowban-alerts:latest
    volumes:
      - './crontab:/app/crontab'
      - './ShadowbanAlerts.json:/app/ShadowbanAlerts.json'
    environment:
      - TZ=Asia/Tokyo
      - SCREEN_NAMES=@iam_takagi,@919takagi,@iamtakagi_ai,@nyanpassnanon
      - WEBHOOK_URL=https://discord.com/api/webhooks/xxx/xxx