version: '3'
services:

  postgres:
    container_name: twichat_postgres
    image: postgres
    environment:
      POSTGRES_USER: twichat
      POSTGRES_PASSWORD: twichat
      POSTGRES_DB: twichat
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - internal_network
    command: -p 5433

  web:
    container_name: twichat_web
    image: ghcr.io/iamtakagi/twichat_web:latest
    environment:
      TZ: Asia/Tokyo
      PORT: 3500
    networks:
      - external_network
    depends_on:
      - backend

  backend:
    container_name: twichat_backend
    image: ghcr.io/iamtakagi/twichat_backend:latest
    volumes:
      - ./backend/log/gunicorn:/app/log/gunicorn
    environment:
      - POSTGRES_DB=twichat
      - POSTGRES_USER=twichat
      - POSTGRES_PASSWORD=twichat
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5433
      - SECRET_KEY=secret
      - DEBUG=false
      - TWITTER_API_CONKEY=xxx
      - TWITTER_API_CONSEC=xxx
      - BACKEND_HOSTNAME=twichat.app
      - WEBPAGE_BASE_URL=https://twichat.app
    command: >
      /bin/bash -c "
      python manage.py migrate &&
      gunicorn -c /app/gunicorn.py twichat.wsgi"
    networks:
      - internal_network
      - external_network
    depends_on:
      - postgres

networks:
    external_network:
      external: true
    internal_network:
      internal: true