version: '3'

services:
  app:
    container_name: anime-title-gacha
    image: ghcr.io/iamtakagi/anime-title-gacha:latest
    environment:
      - TZ=Asia/Tokyo
      - PORT=4600
      - ANNICT_TOKEN=xxx
    restart: unless-stopped
    networks:
      - external_network

networks:
  external_network:
    external: true